// import day1 from './1/index';
// import day2 from './2/index';
// import day3 from './3/index';
// import day4 from './4/index';
// import day5 from './5/index';
// import day6 from './6/index';
// import day7 from './7/index';
// import day8 from './8/index';
// import day9 from './9/index';
import day10 from './10/index';
import day11 from './11/index';

// console.log(`Day 1: ${day1.part1Answer}, ${day1.part2Answer}`);
// console.log(`Day 2: ${day2.part1Answer}, ${day2.part2Answer}`);
// console.log(`Day 3: ${day3.part1Answer}, ${day3.part2Answer}`);
// console.log(`Day 4: ${day4.part1Answer}, ${day4.part2Answer}`);
// console.log(`Day 5: ${day5.part1Answer}, ${day5.part2Answer}`);
// console.log(`Day 6: ${day6.part1Answer}, ${day6.part2Answer}`);
// console.log(`Day 7: ${day7.part1Answer}, ${day7.part2Answer}`);
// console.log(`Day 8: ${day8.part1Answer}, ${day8.part2Answer}`);
// console.log(`Day 9: ${day9.part1Answer}, ${day9.part2Answer}`);
console.log(`Day 10: ${day10.part1Answer}, ${day10.part2Answer}`);
console.log(`Day 11: ${day11.part1Answer}, ${day11.part2Answer}`);
